---
booktitle: Proceedings of Thirty Eighth Conference on Learning Theory
shortname: COLT
sections:
- name: Preface
  title: Preface
- name: Original Papers
  title: Original Papers
- name: Open Problems
  title: Open Problems
volume: '291'
year: '2025'
published: 2025-07-02
start: &1 2025-06-30
end: 2025-07-04
conference_number: '38'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: COLT2025
month: 0
cycles: false
bibtex_editor: Haghtalab, Nika and Moitra, Ankur
editor:
- given: Nika
  family: Haghtalab
- given: Ankur
  family: Moitra
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Thirty Eighth Conference on Learning Theory
    Held in Lyon, France on 30 June to 04 July 2025

  Published as Volume 291 by the Proceedings of Machine Learning Research on 02 July 2025.

  Volume Edited by:
    Nika Haghtalab
    Ankur Moitra

  Series Editors:
    Neil D. Lawrence
date_str: 30 Jun--04 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v291"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v291
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v291
email: ''
conference:
  name: The Thirty Eighth Annual Conference on Learning Theory
  url: https://learningtheory.org/colt2025/
  location: Lyon, France
  dates:
  - *1
  - 2025-07-01
  - 2025-07-02
  - 2025-07-03
  - 2025-07-04
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: colt2025.bib
# Site settings
# Original source:  colt2025.bib
